<?php
/**
 * UPOS Blocks Support
 *
 * Registers the payment method for WooCommerce Blocks (Checkout Block).
 *
 * @package UPOS_WooCommerce
 */

defined( 'ABSPATH' ) || exit;

use Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType;

final class UPOS_Blocks_Support extends AbstractPaymentMethodType {

  protected $name = 'upos';
  private $gateway;

  public function initialize() {
    $this->settings = get_option( 'woocommerce_upos_settings', array() );
    $this->gateway  = new UPOS_Gateway();

    add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_styles' ) );

    // Store API hook to grab payment data from block-based checkouts.
    add_action(
      'woocommerce_store_api_checkout_update_order_from_request',
      array( $this, 'update_order_from_request' ),
      10,
      2
    );
  }

  /**
   * Enqueue frontend styles
   */
  public function enqueue_styles() {
    $style_url  = UPOS_PLUGIN_URL . 'assets/js/blocks/woocommerce-gateway.css';
    $style_path = UPOS_PLUGIN_PATH . 'assets/js/blocks/woocommerce-gateway.css';

    if ( file_exists( $style_path ) ) {
      wp_enqueue_style(
          'upos-blocks-integration-style',
          $style_url,
          array( 'wc-blocks-style' ), // Add dependency to ensure loading order
          UPOS_VERSION
        );
    }
  }

  /**
   * Returns if this payment method should be active. If false, the scripts will not be enqueued.
   *
   * @return boolean
   */
  public function is_active() {
    return $this->gateway && $this->gateway->is_available();
  }

  /**
   * Returns an array of script handles to enqueue for this payment method.
   *
   * @return array
   */
  public function get_payment_method_script_handles() {
    $script_url        = UPOS_PLUGIN_URL . 'assets/js/blocks/upos-blocks.js';
    $script_asset_path = UPOS_PLUGIN_PATH . 'assets/js/blocks/upos-blocks.asset.php';

    // Check if asset file exists (generated by wp-scripts or vite build)
    // Since we use Vite, we might need to handle dependencies manually or generate asset file
    $script_asset = file_exists( $script_asset_path )
    ? require $script_asset_path
    : array(
      'dependencies' => array(
        'wp-data',
        'wp-element',
        'wp-html-entities',
        'wp-i18n',
        'wc-blocks-registry',
        'wc-settings',
      ),
      'version'      => UPOS_VERSION,
    );

    wp_register_script(
      'upos-blocks-integration',
      $script_url,
      $script_asset['dependencies'],
      $script_asset['version'],
      true
    );

    if ( function_exists( 'wp_set_script_translations' ) ) {
      wp_set_script_translations( 'upos-blocks-integration', 'upos-woocommerce', UPOS_PLUGIN_PATH . 'languages' );
    }

    return array( 'upos-blocks-integration' );
  }

  /**
   * Returns an array of key-value pairs of data made available to the payment methods script.
   *
   * @return array
   */
  public function get_payment_method_data() {
    $api = $this->gateway->get_api();

    return array(
      'title'       => $this->gateway->title,
      'description' => $this->gateway->description,
      'supports'    => array_filter( $this->gateway->supports, array( $this->gateway, 'supports' ) ),
      'ajax_url'    => admin_url( 'admin-ajax.php' ),
      'nonce'       => wp_create_nonce( 'upos_get_currencies' ),
      'plugin_url'  => UPOS_PLUGIN_URL,
      'testmode'    => $api ? $api->is_testmode() : false,
    );
  }

    /**
     * Save payment data from Store API to order meta.
     *
     * @param \WC_Order $order Order object.
     * @param \WP_REST_Request $request Request object.
     */
  public static function update_order_from_request( $order, $request ) {
    if ( 'upos' !== $order->get_payment_method() ) {
      return;
    }

    $payment_data = $request['payment_data'] ?? array();

    UPOS_Logger::debug( 'Store API - Saving payment data to order #' . $order->get_id() . ': ' . wp_json_encode( $payment_data ) );

    // Handle associative array (simple key-value pairs from Object)
    if ( isset( $payment_data['upos_currency'] ) ) {
        $order->update_meta_data( '_upos_currency', sanitize_text_field( $payment_data['upos_currency'] ) );
    }
    if ( isset( $payment_data['upos_network'] ) ) {
        $order->update_meta_data( '_upos_network', sanitize_text_field( $payment_data['upos_network'] ) );
    }

    // Handle array of objects { key: "...", value: "..." }
    foreach ( $payment_data as $data_item ) {
      if ( ! is_array( $data_item ) || ! isset( $data_item['key'], $data_item['value'] ) ) {
          continue;
      }

        $key   = $data_item['key'];
        $value = $data_item['value'];

      if ( 'upos_currency' === $key ) {
          $order->update_meta_data( '_upos_currency', sanitize_text_field( $value ) );
      } elseif ( 'upos_network' === $key ) {
          $order->update_meta_data( '_upos_network', sanitize_text_field( $value ) );
      }
    }

    $order->save();
  }

    /**
     * Get the schema for the payment data.
     *
     * @return array
     */
  public function get_payment_data_schema() {
      return array(
        'upos_currency' => array(
          'type' => 'string',
          'arg_options' => array(
            'sanitize_callback' => 'sanitize_text_field',
          ),
        ),
        'upos_network' => array(
          'type' => 'string',
          'arg_options' => array(
            'sanitize_callback' => 'sanitize_text_field',
          ),
        ),
        'wc-upos-new-payment-method' => array(
          'type' => 'string',
          'arg_options' => array(
            'sanitize_callback' => 'sanitize_text_field',
          ),
        ),
      );
  }
}
